name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cargo version
      run: cargo --version
    - name: install nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --locked --features experimental
    - name: Run clippy
      run: cargo clippy --all-targets --locked
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Build (various features)
      run: |
        cargo build --verbose --no-default-features
        cargo +nightly build --verbose --no-default-features --features alloc
        cargo build --verbose --no-default-features --features std
        cargo build --verbose --no-default-features --features hash
        cargo build --verbose --no-default-features --features ord
        cargo build --verbose --no-default-features --features experimental
        cargo build --verbose --all-features
    - name: Document
      run: cargo doc --verbose
    - name: benchmark
      run: ./bench.sh | tee gha-bench.txt
    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Benchmark result (shogi_legality_lite)
        tool: cargo
        output-file-path: gha-bench.txt
        auto-push: false
    - name: Push benchmark result
      run: git push 'https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/rust-shogi-crates/shogi_core.git' gh-pages:gh-pages
      if: github.event_name != 'pull_request'
